// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CancelConvert():Promise<void>;

export function ConvertPDF(arg1:string,arg2:app.ConvertConfig):Promise<app.ConvertResult>;

export function GetPDFInfo(arg1:string):Promise<app.PDFInfo>;

export function GetPagePreview(arg1:string,arg2:number):Promise<string>;

export function OpenPDFDialog():Promise<string>;

export function SelectOutputDir():Promise<string>;
