// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelConvert():Promise<void>;

export function ConvertPDF(arg1:string,arg2:main.ConvertConfig):Promise<main.ConvertResult>;

export function GetPDFInfo(arg1:string):Promise<main.PDFInfo>;

export function GetPagePreview(arg1:string,arg2:number):Promise<string>;

export function OpenPDFDialog():Promise<string>;

export function SelectOutputDir():Promise<string>;
