// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertPDF'](arg1, arg2);
}

export function GetPDFInfo(arg1) {
  return window['go']['main']['App']['GetPDFInfo'](arg1);
}

export function GetPagePreview(arg1, arg2) {
  return window['go']['main']['App']['GetPagePreview'](arg1, arg2);
}

export function OpenPDFDialog() {
  return window['go']['main']['App']['OpenPDFDialog']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}
